Pr/save values to database
mangoweb-sylius/SyliusContactFormPlugin pull request #1
Opened 2019-12-12 11:00 UTC by eliatib

2019-12-12 15:19 UTC, ondrej-kuhnel requested changes

2019-12-12 15:19 UTC, ondrej-kuhnel commented on composer.json
> +            "MangoSylius\\ContactFormPlugin\\": "src/",
Better use `SyliusContactFormPlugin`

2019-12-12 15:19 UTC, ondrej-kuhnel commented on README.md
> +2. Register `\MangoSylius\ContactFormPlugin\MangoSyliusOrderCommentsPlugin` in your Kernel.
Update whole readme

2019-12-12 15:19 UTC, ondrej-kuhnel commented on src/Resources/config/services.yml
> +
Remove blank lines

2019-12-12 15:19 UTC, ondrej-kuhnel commented on src/Resources/config/services.yml
> +  _defaults:
always use 4 spaces

2019-12-12 15:19 UTC, ondrej-kuhnel commented on src/Form/Type/ContactFormType.php
> +                    'required' => true,
wrong location :)
moving it up a level

2019-12-12 15:19 UTC, ondrej-kuhnel commented on src/Entity/ContactFormMessage.php
> + * @ORM\Table(name="app_contact_form")
Start with bundle name

2019-12-12 15:19 UTC, ondrej-kuhnel commented on src/Entity/ContactFormMessage.php
> +    protected $sendTime;
better name `createdAt`

2019-12-12 15:19 UTC, ondrej-kuhnel commented on src/Entity/ContactFormMessage.php
> +class ContactFormMessage implements ResourceInterface
Add column IP

2019-12-12 15:19 UTC, ondrej-kuhnel commented on src/Controller/ContactFormController.php
> +                $SM = $this->adminUserRepository->find(1);
Why this?
Remove it :)

2019-12-13 10:48 UTC, eliatib commented on composer.json
> +            "MangoSylius\\ContactFormPlugin\\": "src/",
DONE

2019-12-13 10:49 UTC, eliatib commented on README.md
> +2. Register `\MangoSylius\ContactFormPlugin\MangoSyliusOrderCommentsPlugin` in your Kernel.
DONE

2019-12-13 10:49 UTC, eliatib commented on src/Resources/config/services.yml
> +
DONE

2019-12-13 10:49 UTC, eliatib commented on src/Resources/config/services.yml
> +  _defaults:
DONE

2019-12-13 10:49 UTC, eliatib commented on src/Form/Type/ContactFormType.php
> +                    'required' => true,
DONE

2019-12-13 10:49 UTC, eliatib commented on src/Entity/ContactFormMessage.php
> + * @ORM\Table(name="app_contact_form")
DONE

2019-12-13 10:49 UTC, eliatib commented on src/Entity/ContactFormMessage.php
> +    protected $sendTime;
DONE

2019-12-13 10:50 UTC, eliatib commented on src/Entity/ContactFormMessage.php
> +class ContactFormMessage implements ResourceInterface
DONE

2019-12-13 10:50 UTC, eliatib commented on src/Controller/ContactFormController.php
> +                $SM = $this->adminUserRepository->find(1);
DONE

2019-12-13 11:14 UTC, ondrej-kuhnel commented on src/Resources/config/services.yml
> +  _defaults:
in every *.yml and *.yaml file

2019-12-13 11:15 UTC, ondrej-kuhnel commented on src/Resources/config/services.yml
> +
in every *.yml and *.yaml file

2019-12-13 11:17 UTC, ondrej-kuhnel commented on src/Entity/ContactFormMessage.php
> + * @ORM\Table(name="app_contact_form")
`app_contact_form_message`

2019-12-13 11:19 UTC, ondrej-kuhnel requested changes

2019-12-13 11:19 UTC, ondrej-kuhnel commented on src/Controller/ContactFormController.php
> +        SenderInterface $mailer,
Remove all unused variables

2019-12-13 11:32 UTC, eliatib commented on src/Resources/config/services.yml
> +  _defaults:
DONE

2019-12-13 11:34 UTC, eliatib commented on src/Entity/ContactFormMessage.php
> + * @ORM\Table(name="app_contact_form")
DONE

2019-12-13 11:35 UTC, eliatib commented on src/Controller/ContactFormController.php
> +        SenderInterface $mailer,
DONE

2019-12-13 11:35 UTC, eliatib commented on src/Resources/config/services.yml
> +
DONE

2019-12-13 11:39 UTC, ondrej-kuhnel approved these changes
squash it and merge

2019-12-13 12:07 UTC, merged